Repository ibexa/rest, pull requests merged in 2023-04, with the labels that each got.

#59 IBX-4929: Removed @internal from Controller\JWT
  src/lib/Server/Controller/JWT.php
Labels: Ready for MERGE

#54 IBX-5296: Added REST serializer service
  src/bundle/Resources/config/services.yml
  src/bundle/Serializer/SerializerFactory.php
  src/lib/Output/Generator/Json/FieldTypeHashGenerator.php
  src/lib/Output/Generator/Xml/FieldTypeHashGenerator.php
  tests/lib/Output/Generator/FieldTypeHashGeneratorBaseTest.php
  tests/lib/Output/Generator/Json/FieldTypeHashGeneratorTest.php
  tests/lib/Output/Generator/Xml/FieldTypeHashGeneratorTest.php
  tests/lib/Output/Generator/_fixtures/Json_FieldTypeHashGeneratorTest__testGenerateUsingNormalizer.out
  tests/lib/Output/Generator/_fixtures/Json_FieldTypeHashGeneratorTest__testGenerateWithMissingNormalizer.out
  tests/lib/Output/Generator/_fixtures/Xml_FieldTypeHashGeneratorTest__testGenerateUsingNormalizer.out
  tests/lib/Output/Generator/_fixtures/Xml_FieldTypeHashGeneratorTest__testGenerateWithMissingNormalizer.out
  tests/lib/Output/ValueObjectVisitorBaseTest.php
Labels: Improvement, QA approved

#60 IBX-5387: Handled not accessible Location in `RelationProcessor`
  src/lib/FieldTypeProcessor/BaseRelationProcessor.php
  tests/lib/FieldTypeProcessor/RelationProcessorTest.php
Labels: Bug, QA approved, Ready for MERGE
