Repository ibexa/rest, pull requests merged in 2024-08, with the labels that each got.

#122 [CS] Improved implementation of UserMetadata criterion parser
  src/lib/Server/Input/Parser/Criterion/UserMetadata.php
Labels: Ready for MERGE, Ready for review

#116 IBX-8596: Added BaseCriterionProcessor
  src/bundle/Resources/config/services.yml
  src/contracts/Input/Parser/Query/Criterion/BaseCriterionProcessor.php
  src/contracts/Input/Parser/Query/Criterion/CriterionProcessorInterface.php
Labels: Improvement, Ready for QA

#127 Added missing strict types declaration to BaseCriterionProcessor
  src/contracts/Input/Parser/Query/Criterion/BaseCriterionProcessor.php
Labels: Improvement, Ready for MERGE, Ready for review

#118 IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists
  src/bundle/CorsOptions/RestProvider.php
  src/bundle/DependencyInjection/Configuration.php
  src/bundle/EventListener/UserCheckRequestListener.php
  src/bundle/Routing/OptionsLoader.php
  src/contracts/Output/Visitor.php
  src/lib/Security/Authenticator/RestAuthenticator.php
  src/lib/Server/Controller/Content.php
  src/lib/Server/Controller/SessionController.php
  src/lib/Server/Security/JWTUser.php
  tests/bundle/EventListener/ResponseListenerTest.php
  tests/lib/Output/VisitorTest.php
Labels: Ready for review
