Repository ibexa/rest, pull requests merged in 2024-09, with the labels that each got.

#132 IBX-8603: Allow deeper media-type granulation
  src/bundle/Resources/config/services.yml
Labels: Ready for review

#124 IBX-8825: Added `strict_mode` for REST API
  phpstan-baseline.neon
  src/bundle/DependencyInjection/Configuration.php
  src/bundle/DependencyInjection/IbexaRestExtension.php
  src/bundle/Resources/config/services.yml
  src/lib/Output/Generator/Json/FieldTypeHashGenerator.php
  src/lib/Output/Generator/Xml/FieldTypeHashGenerator.php
Labels: DX, Ready for review

#117 IBX-8597: Added BaseSortClauseProcessor
  src/bundle/Resources/config/services.yml
  src/contracts/Input/Parser/Query/SortClause/BaseSortClauseProcessor.php
  src/contracts/Input/Parser/Query/SortClause/SortClauseProcessorInterface.php
Labels: Improvement, QA approved

#129 IBX-8535: Deprecate RequestParser and implementations
  src/lib/RequestParser.php
  src/lib/RequestParser/EzPublish.php
  src/lib/RequestParser/Pattern.php
Labels: Ready for review
