Repository ibexa/rest, pull requests merged in 2024-07, with the labels that each got.

#113 Regenerated PHPStan and fixed unit tests
  phpstan-baseline-7.4.neon
  phpstan-baseline-8.0.neon
  phpstan-baseline.neon
  tests/lib/Server/Input/Parser/FieldDefinitionUpdateTest.php
Labels: Ready for review

#100 IBX-8173: Implemented routing language expression parsing media type from `Content-Type` header
  phpstan-baseline.neon
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services.yml
  src/bundle/Routing/ExpressionLanguage/ContentTypeHeaderMatcherExpressionFunction.php
  src/bundle/Routing/OptionsLoader/Mapper.php
  src/contracts/Input/MediaTypeParser.php
  src/contracts/Input/MediaTypeParserInterface.php
  tests/bundle/Functional/HttpOptionsTest.php
  tests/bundle/Routing/ExpressionLanguage/ContentTypeHeaderMatcherExpressionFunctionTest.php
  tests/bundle/Routing/OptionsLoader/RouteCollectionMapperTest.php
  tests/lib/Input/MediaTypeParserTest.php
Labels: Feature, QA approved

#95 IBX-8176: OpenAPI compatible location moving endpoint
  phpstan-baseline.neon
  src/bundle/Resources/config/input_parsers.yml
  src/bundle/Resources/config/routing.yml
  src/lib/Server/Controller/Location.php
  src/lib/Server/Input/Parser/MoveLocation.php
  src/lib/Server/Validation/Builder/Input/Parser/MoveLocationInputValidatorBuilder.php
  tests/bundle/Functional/HttpOptionsTest.php
  tests/bundle/Functional/LocationTest.php
  tests/lib/Server/Input/Parser/MoveLocationTest.php
Labels: Feature, QA approved

#102 IBX-8179: OpenAPI compatible publish role endpoint
  src/bundle/Resources/config/routing.yml
  tests/bundle/Functional/HttpOptionsTest.php
Labels: Feature, Ready for MERGE

#103 IBX-8178: OpenAPI compatible publish content type endpoint
  src/bundle/Resources/config/routing.yml
  tests/bundle/Functional/HttpOptionsTest.php
Labels: Feature, Ready for MERGE

#104 IBX-8177: OpenAPI compatible publish content version endpoint
  src/bundle/Resources/config/routing.yml
  tests/bundle/Functional/HttpOptionsTest.php
Labels: Feature, Ready for MERGE

#105 IBX-8171: Open API compatible create draft from current version endpoint
  src/bundle/Resources/config/routing.yml
  tests/bundle/Functional/HttpOptionsTest.php
Labels: Feature, Ready for MERGE

#106 IBX-8170: Open API compatible create draft from version endpoint
  src/bundle/Resources/config/routing.yml
  tests/bundle/Functional/HttpOptionsTest.php
Labels: Feature, Ready for MERGE

#109 IBX-8174: OpenAPI compatible restore trash item endpoint
  src/bundle/Resources/config/input_parsers.yml
  src/bundle/Resources/config/routing.yml
  src/lib/Server/Controller/Trash.php
  src/lib/Server/Input/Parser/RestoreTrashItemInput.php
  src/lib/Server/Validation/Builder/Input/Parser/RestoreTrashItemInputValidatorBuilder.php
  tests/bundle/Functional/HttpOptionsTest.php
  tests/bundle/Functional/TrashTest.php
  tests/lib/Server/Input/Parser/RestoreTrashItemInputTest.php
Labels: Feature, QA approved

#115 IBX-8368: Implement dedicated location trashing endpoint
  src/bundle/Resources/config/routing.yml
  src/lib/Server/Controller/Trash.php
  tests/bundle/Functional/HttpOptionsTest.php
  tests/bundle/Functional/TrashTest.php
Labels: Doc needed, Feature, QA approved

#119 IBX-8174: Fixed restore trash item response codes to match the spec
  src/lib/Server/Controller/Trash.php
  tests/bundle/Functional/TrashTest.php
Labels: Improvement, QA approved

#108 IBX-8175: OpenAPI compatible move user group endpoint
  src/bundle/Resources/config/input_parsers.yml
  src/bundle/Resources/config/routing.yml
  src/lib/Server/Controller/User.php
  src/lib/Server/Input/Parser/MoveUserGroupInput.php
  src/lib/Server/Validation/Builder/Input/Parser/MoveUserGroupInputValidatorBuilder.php
  tests/bundle/Functional/HttpOptionsTest.php
  tests/bundle/Functional/UserTest.php
  tests/lib/Server/Input/Parser/MoveUserGroupInputTest.php
Labels: Feature, QA approved

#110 IBX-8172: OpenAPI compatible location copy endpoint
  src/bundle/Resources/config/input_parsers.yml
  src/bundle/Resources/config/routing.yml
  src/lib/Server/Controller/Location.php
  src/lib/Server/Input/Parser/CopyLocationInput.php
  src/lib/Server/Validation/Builder/Input/Parser/CopyLocationInputValidatorBuilder.php
  tests/bundle/Functional/HttpOptionsTest.php
  tests/bundle/Functional/LocationTest.php
  tests/bundle/Functional/SearchView/Criterion/IsContainerTest.php
  tests/bundle/Functional/SearchView/Criterion/IsUserBasedTest.php
  tests/bundle/Functional/SearchView/Criterion/ObjectStateIdentifierTest.php
  tests/bundle/Functional/SearchView/Criterion/SectionIdentifierTest.php
  tests/lib/Server/Input/Parser/CopyLocationInputTest.php
Labels: Feature, QA approved

#111 IBX-8169: OpenAPI compatible content copy endpoint
  src/bundle/Resources/config/input_parsers.yml
  src/bundle/Resources/config/routing.yml
  src/lib/Server/Controller/Content.php
  src/lib/Server/Input/Parser/CopyContentInput.php
  src/lib/Server/Validation/Builder/Input/Parser/CopyContentInputValidatorBuilder.php
  tests/bundle/Functional/ContentTest.php
  tests/bundle/Functional/HttpOptionsTest.php
  tests/bundle/Functional/SearchView/Criterion/IsContainerTest.php
  tests/bundle/Functional/SearchView/Criterion/IsUserBasedTest.php
  tests/bundle/Functional/SearchView/Criterion/ObjectStateIdentifierTest.php
  tests/bundle/Functional/SearchView/Criterion/SectionIdentifierTest.php
  tests/lib/Server/Input/Parser/CopyContentInputTest.php
Labels: Feature, QA approved
