Repository ibexa/rest, pull requests merged in 2025-02, with the labels that each got.

#145 IBX-9587: Fixed failing REST requests after Symfony 6 upgrade
  src/bundle/Resources/config/routing.yml
  src/bundle/Routing/OptionsLoader/Mapper.php
  tests/bundle/Functional/BookmarkTest.php
  tests/bundle/Functional/LocationTest.php
  tests/bundle/Routing/OptionsLoader/MapperTest.php
Labels: Ready for QA

#121 IBX-8190: Add Symfony's Serializer support
  phpstan-baseline.neon
  src/bundle/DependencyInjection/Compiler/ValueObjectVisitorResolverPass.php
  src/bundle/DependencyInjection/IbexaRestExtension.php
  src/bundle/IbexaRestBundle.php
  src/bundle/Resources/config/serializer.yaml
  src/bundle/Resources/config/services.yml
  src/contracts/Output/Generator.php
  src/contracts/Output/ValueObjectVisitorDispatcher.php
  src/contracts/Output/ValueObjectVisitorResolver.php
  src/contracts/Output/ValueObjectVisitorResolverInterface.php
  src/contracts/Output/Visitor.php
  src/contracts/Output/VisitorAdapterNormalizer.php
  src/lib/Output/Generator/AbstractFieldTypeHashGenerator.php
  src/lib/Output/Generator/Data/ArrayList.php
  src/lib/Output/Generator/Data/DataObjectInterface.php
  src/lib/Output/Generator/Json.php
  src/lib/Output/Generator/Json/ArrayObject.php
  src/lib/Output/Generator/Json/FieldTypeHashGenerator.php
  src/lib/Output/Generator/Json/JsonObject.php
  src/lib/Output/Generator/Xml.php
  src/lib/Output/Generator/Xml/FieldTypeHashGenerator.php
  src/lib/Output/Normalizer/ArrayListNormalizer.php
  src/lib/Output/Normalizer/ArrayObjectNormalizer.php
  src/lib/Output/Normalizer/JsonObjectNormalizer.php
  src/lib/Output/Normalizer/JsonSerializableNormalizer.php
  tests/bundle/DependencyInjection/Compiler/ValueObjectVisitorResolverPassTest.php
  tests/integration/IbexaTestKernel.php
  tests/integration/Resources/services.yaml
  tests/integration/Serializer/SerializerTest.php
  tests/integration/Serializer/TestDataObject.php
  tests/integration/Serializer/TestDataObjectNormalizer.php
  tests/integration/Serializer/_snapshot/TestDataObject.json
  tests/integration/Serializer/_snapshot/TestDataObject.xml
  tests/integration/bootstrap.php
  tests/lib/Output/Generator/FieldTypeHashGeneratorBaseTest.php
  tests/lib/Output/Generator/XmlTest.php
  tests/lib/Output/Generator/_fixtures/Xml_FieldTypeHashGeneratorTest__testGenerateStringValueWithSpecialChars.out
  tests/lib/Output/Generator/_fixtures/testGeneratorDocument.xml
  tests/lib/Output/Generator/_fixtures/testGeneratorHashElement.xml
  tests/lib/Output/Generator/_fixtures/testStartValueElementWithAttributes/booleans.xml
  tests/lib/Output/Normalizer/ArrayListNormalizerTest.php
  tests/lib/Output/ValueObjectVisitorBaseTest.php
  tests/lib/Output/ValueObjectVisitorDispatcherTest.php
  tests/lib/Output/VisitorTest.php
  tests/lib/Server/Output/ValueObjectVisitor/LocationTest.php
Labels: Doc needed, Feature, Ready for QA

#147 IBX-8190: Fix normalizers' priorities
  src/bundle/Resources/config/serializer.yaml
Labels: Bug, Ready for review

#114 IBX-8335: API Platform v4 integration
  composer.json
  src/bundle/ApiPlatform/ClassNameResourceNameCollectionFactory.php
  src/bundle/ApiPlatform/OpenApiFactory.php
  src/bundle/ApiPlatform/SchemasCollectionFactory.php
  src/bundle/DependencyInjection/Compiler/ClassNameResourceNamePass.php
  src/bundle/DependencyInjection/Compiler/SchemaProviderPass.php
  src/bundle/DependencyInjection/IbexaRestExtension.php
  src/bundle/IbexaRestBundle.php
  src/bundle/Resources/api_platform/base_schemas.yml
  src/bundle/Resources/api_platform/examples/languages/GET/LanguageList.json.example
  src/bundle/Resources/api_platform/examples/languages/GET/LanguageList.xml.example
  src/bundle/Resources/api_platform/examples/languages/code/GET/Language.json.example
  src/bundle/Resources/api_platform/examples/languages/code/GET/Language.xml.example
  src/bundle/Resources/api_platform/language_schemas.yml
  src/bundle/Resources/config/api_platform.yml
  src/bundle/Resources/config/routing.yml
  src/bundle/Resources/config/services.yml
  src/lib/ApiPlatform/SchemasCollection.php
  src/lib/ApiPlatform/SchemasCollectionFactoryInterface.php
  src/lib/ApiPlatform/SchemasProvider.php
  src/lib/ApiPlatform/SchemasProviderInterface.php
  src/lib/Server/Controller/Language.php
  tests/integration/IbexaTestKernel.php
Labels: Feature, Ready for MERGE
