Repository ibexa/rest, pull requests merged in 2025-07, with the labels that each got.

#180 IBX-8540: Fixed building content type field def. list response
  phpstan-baseline.neon
  src/lib/Server/Controller/ContentType.php
Labels: QA approved

#160 IBX-9678: JsonSerializableNormalizer return type mismatch causing 500 error
  src/bundle/Resources/config/serializer.yaml
  src/lib/Output/Normalizer/JsonSerializableNormalizer.php
Labels: Bug, Ready for QA

#178 IBX-8677: Cast location to integer in copying content action
  phpstan-baseline.neon
  src/lib/Server/Controller/Content.php
Labels: Bug, QA approved
