Repository ibexa/rest, pull requests merged in 2025-03, with the labels that each got.

#149 Refactored ContentType::isContainer property to method changed
  src/lib/Server/Output/ValueObjectVisitor/RestContentType.php
Labels: Ready for review

#151 Bumped `api-platform/core` to `4.1`
  composer.json
  src/bundle/DependencyInjection/IbexaRestExtension.php
Labels: Improvement, Ready for MERGE

#153 IBX-8778: API Platform schema fixes
  src/bundle/Resources/api_platform/schemas/base_schemas.yml
  src/bundle/Resources/api_platform/schemas/content_types_schemas.yml
  src/bundle/Resources/api_platform/schemas/language_schemas.yml
  src/lib/Server/Controller/Bookmark/BookmarkListController.php
  src/lib/Server/Controller/Content/ContentCurrentVersionRelationsRedirectController.php
  src/lib/Server/Controller/Content/ContentRedirectController.php
  src/lib/Server/Controller/Content/ContentVersionsListController.php
  src/lib/Server/Controller/ContentType/ContentTypeDraftFieldDefinitionDeleteController.php
  src/lib/Server/Controller/ContentType/ContentTypeListController.php
  src/lib/Server/Controller/ContentType/ContentTypeListForGroupController.php
  src/lib/Server/Controller/Language/LanguageListController.php
  src/lib/Server/Controller/Language/LanguageLoadByIdController.php
  src/lib/Server/Controller/ObjectState/ObjectStateGroupListController.php
  src/lib/Server/Controller/ObjectState/ObjectStateListController.php
  src/lib/Server/Controller/ObjectState/ObjectStatesForContentListController.php
  src/lib/Server/Controller/Role/RoleAssignmentForUserGroupListController.php
  src/lib/Server/Controller/Role/RoleAssignmentForUserGroupLoadByIdController.php
  src/lib/Server/Controller/Role/RoleAssignmentForUserListController.php
  src/lib/Server/Controller/Role/RoleAssignmentForUserLoadByIdController.php
  src/lib/Server/Controller/Role/RoleDeleteController.php
  src/lib/Server/Controller/Role/RoleDraftDeleteController.php
  src/lib/Server/Controller/Role/RoleListController.php
  src/lib/Server/Controller/Role/RolePoliciesForUserListController.php
  src/lib/Server/Controller/Role/RolePolicyDeleteAllFromRoleController.php
  src/lib/Server/Controller/Role/RoleUnassignFromUserController.php
  src/lib/Server/Controller/Role/RoleUnassignFromUserGroupController.php
  src/lib/Server/Controller/Section/SectionListController.php
  src/lib/Server/Controller/Trash/TrashEmptyController.php
  src/lib/Server/Controller/Trash/TrashItemListController.php
  src/lib/Server/Controller/URLAlias/URLAliasListGlobalController.php
  src/lib/Server/Controller/URLAlias/URLAliasListLocationController.php
  src/lib/Server/Controller/URLWildcard/URLWildcardListController.php
  src/lib/Server/Controller/User/UserDraftListController.php
  src/lib/Server/Controller/User/UserGroupDeleteController.php
  src/lib/Server/Controller/User/UserGroupListController.php
  src/lib/Server/Controller/User/UserGroupOfRootLoadController.php
  src/lib/Server/Controller/User/UserRedirectToCurrentUserController.php
Labels: Bug, Ready for MERGE

#155 IBX-8921: Implemented API Platform Symfony command
  src/bundle/Resources/config/api_platform.yml
Labels: Feature, Ready for MERGE

#154 Disabled API Platform for `prod` environment
  src/bundle/DependencyInjection/IbexaRestExtension.php
  src/bundle/Resources/config/routing.yml
  src/lib/Server/Input/Parser/Criterion/LogicalOperator.php
  src/lib/Server/Input/Parser/Criterion/MoreLikeThis.php
  src/lib/Server/Input/Parser/Criterion/Operator.php
Labels: Bug, Ready for MERGE

#157 IBX-9058: Adapt schemas to OpenAPI 3.1
  src/bundle/Resources/api_platform/schemas/base_schemas.yml
  src/bundle/Resources/api_platform/schemas/content_types_schemas.yml
  src/bundle/Resources/api_platform/schemas/language_schemas.yml
Labels: Bug, Ready for MERGE

#162 Fixed the `views` endpoint
  phpstan-baseline.neon
  src/bundle/Resources/config/services.yml
  src/lib/Server/Controller/Views.php
Labels: Bug, Ready for MERGE
